[package]
name = "dif_btw_squares_additions"
version = "0.1.0"
authors = ["nath54 <=>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
